Repository HexagonLab-s-SilverPlus/react, pull requests merged in 2024-12, with the labels that each got.

#6 각자 맡은 메인기능 구현 및 폴더 구조 리팩토링
  package-lock.json
  package.json
  src/App.js
  src/AuthProvider.js
  src/assets/images/keyboard_arrow_down.png
  src/assets/images/keyboard_arrow_up.png
  src/assets/images/profile.png
  src/assets/images/search.png
  src/components/common/SideBar.js
  src/components/common/SideBar.module.css
  src/components/qna/QNAHeader.js
  src/components/qna/QNAHeader.module.css
  src/components/qna/QNATitle.js
  src/components/qna/QNATitle.module.css
  src/components/sm/senior/common/SeniorFooter.js
  src/components/sm/senior/common/SeniorFooter.module.css
  src/components/sm/senior/common/SeniorNavbar.js
  src/components/sm/senior/common/SeniorNavbar.module.css
  src/index.js
  src/pages/ey/EYmain.js
  src/pages/ey/chat/ChatPage.js
  src/pages/ey/chat/ChatPage.module.css
  src/pages/ey/chat/Container.js
  src/pages/ey/chat/Container.module.css
  src/pages/ey/chat/EYmain.js
  src/pages/ey/chat/EYmain.module.css
  src/pages/notice/NoticeList.js
  src/pages/notice/NoticeList.module.css
  src/pages/qna/QNAList.js
  src/pages/qna/QNAList.module.css
  src/pages/sm/SMmain.js
  src/pages/tj/Enroll.module.css
  src/pages/tj/TJmain.js
  src/routers/eyRouter.js
  src/routers/hsRouter.js
  src/routers/smRouter.js
Labels: documentation

#7 릴리즈 노트 자동화 설정
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: documentation, enhancement

#8 Update release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: bug

#9 Update release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: bug

#10 Update release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: bug

#16 feat: 로그인/로그아웃 기능 구현완료
  src/AuthProvider.js
  src/components/common/SideBar.js
  src/pages/member/Enroll.module.css
  src/pages/member/EnrollManager.js
  src/pages/member/LoginMember.js
  src/pages/member/LoginMember.module.css
  src/pages/qna/QNAList.js
  src/routers/qnaRouter.js
Labels: enhancement

#21 Hs
  src/components/common/Paging.js
  src/pages/qna/QNAList.js
  src/pages/qna/QnAList.module.css
  src/pages/qna/QnAWrite.js
  src/utils/axios.js
Labels: enhancement

#22 refactor: axios url 명칭 수정
  src/utils/axios.js
Labels: enhancement

#23 flx
  src/pages/notice/NoticeWrite.js
  src/pages/qna/QNAList.js
  src/pages/qna/QnAWrite.js
  src/utils/axios.js
Labels: bug
